#! /usr/bin/env node
// Requirement
const 
    fs      = require("fs"), 
    path    = require("path");


// Util Functions
function getValueof(flag) {
    let thatValue   = null,  
        match       = false;
    args.forEach(value => {
        if(match && !value.startsWith("--"))
            thatValue = value;
        match = false;
        if(value == flag)
            match = true;
    });
    return thatValue;
}


// Util Prototypes
String.prototype.toCapitalize = function() {
    return this.charAt(0).toUpperCase() + this.substr(1).toLowerCase();
}
    

// Main Constants
const 
    pathLaunchedCmd     = process.cwd(), 
    rootVueProject      = path.join(pathLaunchedCmd, './src/', 'main.js'), 
    args                = process.argv.filter((value, index) => index >= 2), 
    nodeFile            = process.argv[0], 
    vuegcFile           = process.argv[1], 
    requiredArgs        = {
        name:   getValueof("--name"), 
    }, 
    optionalArgs        = {
        file:       {
            path:   getValueof("--path") || './component/', 
        }, 
        template:   {
            // 
        }, 
        script:     {
            // 
        }, 
        style:      {
            scoped: getValueof("--scoped") || true, 
            style:  getValueof("--style") || "scss", 
        }
    };


async function vuegc() {
    try {
        // Checking for existing of all requried arguments
        for(let arg in requiredArgs) {
            if(requiredArgs[arg] == null)
                throw new Error("Flag " + arg + " required");
        }
    
        // Initializing
        const 
            componentFileName   = requiredArgs.name.toCapitalize(), 
            spanStyle           = `span{ font-weight: bold; }`, 
            aStyle              = `a{ font-style: italic; }`, 
            componentContent    = `
<template>
    <div id="${ componentFileName }"> Component <span>${ componentFileName }</span> generated by <a href="">VueGC</a> </div>
</template>

<script>
export default {
    name: "${ componentFileName }", 
    props: { }, 
    data() { }, 
    methods() { }
}
</script>

<style${ optionalArgs.style.scoped == true && ' scoped' || ''}${ ' lang="' + optionalArgs.style.style +'"' }>
#${ componentFileName }{
    font-size: 16px;
    line-height: 150%;
    ${ ["scss", "sass", "stylus"].includes(optionalArgs.style.style) && "\n" + spanStyle + "\n" + aStyle || "" }
}${ optionalArgs.style.style == "css" && "\n" + spanStyle + "\n" + aStyle || "" }
</style>
            `, 
            pathComponent
    
        // Start to generating vue component
        console.log("> Generating vue component starting");
    
        // Checking if I'm in the root of Vue project
        let content = fs.readFileSync(rootVueProject, { encoding: 'utf-8' });
        if(!content.match(/(new Vue)|(from 'vue')|Vue\./gi))
            throw new Error("It is not the root of Vue project");
        console.log("   This a root of Vue Project");
    
        // Creating the folders for the component
        fs.mkdirSync(path.join(pathLaunchedCmd, optionalArgs.file.path), err => {
            if(err)
                throw err;
            console.log("   New folder(s) created");
        });
    
        // Creating the component
        fs.writeFileSync(path.join(pathLaunchedCmd, "./src/", optionalArgs.file.path, requiredArgs.name.endsWith(".vue") && requiredArgs.name || (requiredArgs.name + ".vue")), componentContent);
    
        // Generate vue component done
        console.log("> Generating vue component success");
    } catch(err) {
        // If error spotted
        console.log("> Generating vue component failure");
        console.log("\n");
        console.error(err);
        process.exit();
    }
}

vuegc();
